### ISSUE TITLE
MogHouse

### ISSUE THREAD

**Issue by bjggi** [PeachBlossomWine/multictrl#3]
Hey there

Is there a way to integrate the Gearswap **world.in_mog_house** function?

A lot of time i use stuff like enter or enup, and my chars in the Mog House are starting hitting on the Moogle :)

Best regards

**Comment by PeachBlossomWine** [comment]
Hmm that's a good idea, I guess can see if I can check in moghouse and not go for those commands.

**Comment by bjggi** [comment]
👍 Think for all the travel and target stuff, that would be useful

**Comment by PeachBlossomWine** [comment]
Will add that in in next update.
