### ISSUE TITLE
Auto-Dispel/Finale function

### ISSUE THREAD

**Issue by MrKayDu** [PeachBlossomWine/multictrl#4]
Looks like a new function, is there a way to disable it? Keeps spamming dispel/finale on Kei's spikes

**Comment by MrKayDu** [comment]
nvm, it's in the healbot update. closing issue here and opening it there

**Comment by PeachBlossomWine** [comment]
hb dispel off

**Comment by PeachBlossomWine** [comment]
just use
//hb dispel off
