### ISSUE TITLE
[MC] ABORT! Wrong NPC interaction! during Superwarp

### ISSUE THREAD

**Issue by Jayddo** [PeachBlossomWine/multictrl#9]
been happening for the last few weeks.

Sometimes I get this error and the warp cancels, some other times it goes through. I am using the original Superwarp, not your fork, not sure if there's any difference.

Not sure why it's happening yet

**Comment by PeachBlossomWine** [comment]
I don't think there's much difference, no one I know has this issue of cancels.  You can only get cancel if you get hit by mobs.

**Comment by PeachBlossomWine** [comment]
IF it's [MC] then check if you have the latest
